### ISSUE TITLE
libpam-systemd is necessary

### ISSUE THREAD

**Issue by szepeviktor** [kylemanna/systemd-utils#3]
Please include in the README that the `libpam-systemd` package needs to be installed.

**Comment by kylemanna** [comment]
For what distribution? Arch linux doesn't have a libpam-systemd package.  Furthermore, what exactly needs the pam library?

**Comment by szepeviktor** [comment]
On Debian based systems.
But there is a bug for installing this package by default.

It is needed to enable user services in systemd.

>  This package contains the PAM module which registers user sessions in the systemd control group hierarchy. 

https://packages.debian.org/jessie/libpam-systemd

**Comment by kylemanna** [comment]
What is the error message without it?  I fear that Debian distributions that don't have necessary facilities to do something as simple as enabling a user service probably isn't setup to fully integrate systemd user sessions and this may be the first of a few battles.

**Comment by szepeviktor** [comment]
Actually I don't use systemd, this is the first server without sysvinit.

The error message said that `Failed to get D-Bus connection: Connection refused`
http://forum.armbian.com/index.php/topic/470-systemctl-user-failed-to-get-d-bus-connection-connection-refused/

**Comment by kylemanna** [comment]
I see.  It's a bug in the upstream distribution as I suspected.  This repository doesn't try to fix all bugs on all distributions.

It appears that upstream has attempted to fix it [here](http://forum.armbian.com/index.php/topic/470-systemctl-user-failed-to-get-d-bus-connection-connection-refused/#entry2936) and [here](http://forum.armbian.com/index.php/topic/470-systemctl-user-failed-to-get-d-bus-connection-connection-refused/#entry2938).

**Comment by kylemanna** [comment]
Hopefully anyone who encounters this bug can find this issue for a hint for a workaround in the interim.
